--- 
abstract: a distro that always fails the `perl Makefile.PL` stage
author: 
  - Martin Thurn <mthurn@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Devel-Fail-MakefilePL
no_index: 
  directory: 
    - inc
    - t
version: 1.010
