---
abstract: 'a distro that always fails the `perl Makefile.PL` stage'
author:
  - 'Martin Thurn, C<mthurn@cpan.org>, L<http://www.sandcrawler.com/SWB/cpan-modules.html>'
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Devel-Fail-MakefilePL
no_index:
  directory:
    - inc
    - t
version: 1.012
